# Generated by Django 5.2.9 on 2025-12-13 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpmodule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='erpmodule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
