# Generated by Django 5.2.9 on 2025-12-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_erpmodule_created_at_erpmodule_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpmodule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
