# Generated by Django 5.2.9 on 2025-12-18 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_erpmodule_is_legacy_erpmodule_legacy_app_label'),
        ('subscriptions', '0003_erpmodule_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='erp_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.erpmodule'),
        ),
    ]
