# Generated by Django 5.2.9 on 2025-12-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_subscription_erp_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('1M', '1 Month'), ('3M', '3 Months'), ('1Y', '1 Year')], default='3M', max_length=2),
        ),
    ]
