# Generated by Django 5.2.9 on 2026-01-10 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=50)),
                ('erp_code', models.CharField(max_length=50)),
                ('upload_type', models.CharField(choices=[('products', 'Products'), ('stock', 'Stock'), ('billing', 'Billing')], max_length=20)),
                ('business_date', models.DateField(blank=True, null=True)),
                ('row_data', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailySalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=50)),
                ('erp_code', models.CharField(max_length=50)),
                ('sale_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ERPModule',
        ),
        migrations.AddIndex(
            model_name='bulkuploadrecord',
            index=models.Index(fields=['tenant_id', 'user', 'erp_code'], name='generic_erp_tenant__79a219_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkuploadrecord',
            index=models.Index(fields=['upload_type'], name='generic_erp_upload__e6e3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkuploadrecord',
            index=models.Index(fields=['business_date'], name='generic_erp_busines_6ce207_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysalessummary',
            unique_together={('tenant_id', 'user', 'erp_code', 'sale_date')},
        ),
    ]
