# Generated by Django 5.2.9 on 2026-01-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_erp', '0002_bulkuploadrecord_dailysalessummary_delete_erpmodule_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bulkuploadrecord',
            name='generic_erp_tenant__79a219_idx',
        ),
        migrations.RemoveIndex(
            model_name='bulkuploadrecord',
            name='generic_erp_upload__e6e3a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='bulkuploadrecord',
            name='generic_erp_busines_6ce207_idx',
        ),
        migrations.AddField(
            model_name='bulkuploadrecord',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='bulkuploadrecord',
            name='upload_type',
            field=models.CharField(max_length=20),
        ),
    ]
