# Generated by Django 5.2.9 on 2026-01-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_erp', '0003_remove_bulkuploadrecord_generic_erp_tenant__79a219_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuploadrecord',
            name='row_data',
            field=models.JSONField(default=dict),
        ),
    ]
