# Generated by Django 5.2.9 on 2025-12-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpmodule',
            name='is_legacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='erpmodule',
            name='legacy_app_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
