# Generated by Django 5.2.9 on 2025-12-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_erpmodule_is_legacy_erpmodule_legacy_app_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpmodule',
            name='icon',
            field=models.CharField(default='layers', max_length=50),
        ),
    ]
